//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WeatherEntities : DbContext
    {
        public WeatherEntities()
            : base("name=WeatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetHumadrar_Result> GetHumadrar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumadrar_Result>("GetHumadrar");
        }
    
        public virtual ObjectResult<GetHumaindefla_Result> GetHumaindefla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumaindefla_Result>("GetHumaindefla");
        }
    
        public virtual ObjectResult<GetHumaintemouchent_Result> GetHumaintemouchent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumaintemouchent_Result>("GetHumaintemouchent");
        }
    
        public virtual ObjectResult<GetHumalger_Result> GetHumalger()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumalger_Result>("GetHumalger");
        }
    
        public virtual ObjectResult<GetHumannaba_Result> GetHumannaba()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumannaba_Result>("GetHumannaba");
        }
    
        public virtual ObjectResult<GetHumbatna_Result> GetHumbatna()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbatna_Result>("GetHumbatna");
        }
    
        public virtual ObjectResult<GetHumbayadh_Result> GetHumbayadh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbayadh_Result>("GetHumbayadh");
        }
    
        public virtual ObjectResult<GetHumbechar_Result> GetHumbechar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbechar_Result>("GetHumbechar");
        }
    
        public virtual ObjectResult<GetHumbejaia_Result> GetHumbejaia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbejaia_Result>("GetHumbejaia");
        }
    
        public virtual ObjectResult<GetHumbiskra_Result> GetHumbiskra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbiskra_Result>("GetHumbiskra");
        }
    
        public virtual ObjectResult<GetHumblida_Result> GetHumblida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumblida_Result>("GetHumblida");
        }
    
        public virtual ObjectResult<GetHumbordj_Result> GetHumbordj()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbordj_Result>("GetHumbordj");
        }
    
        public virtual ObjectResult<GetHumbouira_Result> GetHumbouira()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumbouira_Result>("GetHumbouira");
        }
    
        public virtual ObjectResult<GetHumboumerdes_Result> GetHumboumerdes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumboumerdes_Result>("GetHumboumerdes");
        }
    
        public virtual ObjectResult<GetHumchlef_Result> GetHumchlef()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumchlef_Result>("GetHumchlef");
        }
    
        public virtual ObjectResult<GetHumconsto_Result> GetHumconsto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumconsto_Result>("GetHumconsto");
        }
    
        public virtual ObjectResult<GetHumdjelfa_Result> GetHumdjelfa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumdjelfa_Result>("GetHumdjelfa");
        }
    
        public virtual ObjectResult<GetHumghardaia_Result> GetHumghardaia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumghardaia_Result>("GetHumghardaia");
        }
    
        public virtual ObjectResult<GetHumguelma_Result> GetHumguelma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumguelma_Result>("GetHumguelma");
        }
    
        public virtual ObjectResult<GetHumillizi_Result> GetHumillizi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumillizi_Result>("GetHumillizi");
        }
    
        public virtual ObjectResult<GetHumjijel_Result> GetHumjijel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumjijel_Result>("GetHumjijel");
        }
    
        public virtual ObjectResult<GetHumkhench_Result> GetHumkhench()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumkhench_Result>("GetHumkhench");
        }
    
        public virtual ObjectResult<GetHumlaghouat_Result> GetHumlaghouat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumlaghouat_Result>("GetHumlaghouat");
        }
    
        public virtual ObjectResult<GetHummascara_Result> GetHummascara()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHummascara_Result>("GetHummascara");
        }
    
        public virtual ObjectResult<GetHummedea_Result> GetHummedea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHummedea_Result>("GetHummedea");
        }
    
        public virtual ObjectResult<GetHummila_Result> GetHummila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHummila_Result>("GetHummila");
        }
    
        public virtual ObjectResult<GetHummosta_Result> GetHummosta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHummosta_Result>("GetHummosta");
        }
    
        public virtual ObjectResult<gethummsila_Result> gethummsila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gethummsila_Result>("gethummsila");
        }
    
        public virtual ObjectResult<GetHumnaama_Result> GetHumnaama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumnaama_Result>("GetHumnaama");
        }
    
        public virtual ObjectResult<GetHumoran_Result> GetHumoran()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumoran_Result>("GetHumoran");
        }
    
        public virtual ObjectResult<GetHumoued_Result> GetHumoued()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumoued_Result>("GetHumoued");
        }
    
        public virtual ObjectResult<GetHumouerg_Result> GetHumouerg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumouerg_Result>("GetHumouerg");
        }
    
        public virtual ObjectResult<GetHumoum_Result> GetHumoum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumoum_Result>("GetHumoum");
        }
    
        public virtual ObjectResult<GetHumsaida_Result> GetHumsaida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumsaida_Result>("GetHumsaida");
        }
    
        public virtual ObjectResult<GetHumsetif_Result> GetHumsetif()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumsetif_Result>("GetHumsetif");
        }
    
        public virtual ObjectResult<GetHumsidiabbes_Result> GetHumsidiabbes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumsidiabbes_Result>("GetHumsidiabbes");
        }
    
        public virtual ObjectResult<GetHumskikda_Result> GetHumskikda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumskikda_Result>("GetHumskikda");
        }
    
        public virtual ObjectResult<GetHumsouk_Result> GetHumsouk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumsouk_Result>("GetHumsouk");
        }
    
        public virtual ObjectResult<GetHumtamm_Result> GetHumtamm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumtamm_Result>("GetHumtamm");
        }
    
        public virtual ObjectResult<gethumtebessa_Result> gethumtebessa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gethumtebessa_Result>("gethumtebessa");
        }
    
        public virtual ObjectResult<GetHumtiaret_Result> GetHumtiaret()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumtiaret_Result>("GetHumtiaret");
        }
    
        public virtual ObjectResult<gethumtindouf_Result> gethumtindouf()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gethumtindouf_Result>("gethumtindouf");
        }
    
        public virtual ObjectResult<GetHumtipaza_Result> GetHumtipaza()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumtipaza_Result>("GetHumtipaza");
        }
    
        public virtual ObjectResult<GetHumtissem_Result> GetHumtissem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumtissem_Result>("GetHumtissem");
        }
    
        public virtual ObjectResult<GetHumtizi_Result> GetHumtizi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumtizi_Result>("GetHumtizi");
        }
    
        public virtual ObjectResult<GetHumtlemcen_Result> GetHumtlemcen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHumtlemcen_Result>("GetHumtlemcen");
        }
    
        public virtual ObjectResult<GetHureliz_Result> GetHureliz()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHureliz_Result>("GetHureliz");
        }
    
        public virtual ObjectResult<GetHutaref_Result> GetHutaref()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHutaref_Result>("GetHutaref");
        }
    
        public virtual ObjectResult<GetPreadrar_Result> GetPreadrar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreadrar_Result>("GetPreadrar");
        }
    
        public virtual ObjectResult<GetPreaindefla_Result> GetPreaindefla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreaindefla_Result>("GetPreaindefla");
        }
    
        public virtual ObjectResult<GetPreaintemouchent_Result> GetPreaintemouchent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreaintemouchent_Result>("GetPreaintemouchent");
        }
    
        public virtual ObjectResult<GetPrealger_Result> GetPrealger()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrealger_Result>("GetPrealger");
        }
    
        public virtual ObjectResult<GetPreannaba_Result> GetPreannaba()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreannaba_Result>("GetPreannaba");
        }
    
        public virtual ObjectResult<GetPrebatna_Result> GetPrebatna()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebatna_Result>("GetPrebatna");
        }
    
        public virtual ObjectResult<GetPrebechar_Result> GetPrebechar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebechar_Result>("GetPrebechar");
        }
    
        public virtual ObjectResult<GetPrebejaia_Result> GetPrebejaia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebejaia_Result>("GetPrebejaia");
        }
    
        public virtual ObjectResult<GetPrebiskra_Result> GetPrebiskra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebiskra_Result>("GetPrebiskra");
        }
    
        public virtual ObjectResult<GetPreblida_Result> GetPreblida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreblida_Result>("GetPreblida");
        }
    
        public virtual ObjectResult<GetPrebordj_Result> GetPrebordj()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebordj_Result>("GetPrebordj");
        }
    
        public virtual ObjectResult<GetPrebouira_Result> GetPrebouira()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebouira_Result>("GetPrebouira");
        }
    
        public virtual ObjectResult<GetPreboumerdes_Result> GetPreboumerdes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreboumerdes_Result>("GetPreboumerdes");
        }
    
        public virtual ObjectResult<GetPrebyadh_Result> GetPrebyadh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrebyadh_Result>("GetPrebyadh");
        }
    
        public virtual ObjectResult<GetPrechlef_Result> GetPrechlef()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrechlef_Result>("GetPrechlef");
        }
    
        public virtual ObjectResult<GetPreconsto_Result> GetPreconsto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreconsto_Result>("GetPreconsto");
        }
    
        public virtual ObjectResult<GetPredjelfa_Result> GetPredjelfa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPredjelfa_Result>("GetPredjelfa");
        }
    
        public virtual ObjectResult<GetPreghardaia_Result> GetPreghardaia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreghardaia_Result>("GetPreghardaia");
        }
    
        public virtual ObjectResult<GetPreguelma_Result> GetPreguelma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreguelma_Result>("GetPreguelma");
        }
    
        public virtual ObjectResult<GetPreillizi_Result> GetPreillizi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreillizi_Result>("GetPreillizi");
        }
    
        public virtual ObjectResult<GetPrejijel_Result> GetPrejijel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrejijel_Result>("GetPrejijel");
        }
    
        public virtual ObjectResult<GetPrekhench_Result> GetPrekhench()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrekhench_Result>("GetPrekhench");
        }
    
        public virtual ObjectResult<GetPrelaghouat_Result> GetPrelaghouat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrelaghouat_Result>("GetPrelaghouat");
        }
    
        public virtual ObjectResult<GetPremascara_Result> GetPremascara()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPremascara_Result>("GetPremascara");
        }
    
        public virtual ObjectResult<GetPremedea_Result> GetPremedea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPremedea_Result>("GetPremedea");
        }
    
        public virtual ObjectResult<GetPremila_Result> GetPremila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPremila_Result>("GetPremila");
        }
    
        public virtual ObjectResult<GetPremosta_Result> GetPremosta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPremosta_Result>("GetPremosta");
        }
    
        public virtual ObjectResult<getpremsila_Result> getpremsila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getpremsila_Result>("getpremsila");
        }
    
        public virtual ObjectResult<GetPrenaama_Result> GetPrenaama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrenaama_Result>("GetPrenaama");
        }
    
        public virtual ObjectResult<GetPreoran_Result> GetPreoran()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreoran_Result>("GetPreoran");
        }
    
        public virtual ObjectResult<GetPreoued_Result> GetPreoued()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreoued_Result>("GetPreoued");
        }
    
        public virtual ObjectResult<GetPreouerg_Result> GetPreouerg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreouerg_Result>("GetPreouerg");
        }
    
        public virtual ObjectResult<GetPreoum_Result> GetPreoum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreoum_Result>("GetPreoum");
        }
    
        public virtual ObjectResult<GetPrereliz_Result> GetPrereliz()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPrereliz_Result>("GetPrereliz");
        }
    
        public virtual ObjectResult<GetPresaida_Result> GetPresaida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPresaida_Result>("GetPresaida");
        }
    
        public virtual ObjectResult<GetPresetif_Result> GetPresetif()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPresetif_Result>("GetPresetif");
        }
    
        public virtual ObjectResult<GetPresidiabbes_Result> GetPresidiabbes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPresidiabbes_Result>("GetPresidiabbes");
        }
    
        public virtual ObjectResult<GetPreskikda_Result> GetPreskikda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPreskikda_Result>("GetPreskikda");
        }
    
        public virtual ObjectResult<GetPresouk_Result> GetPresouk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPresouk_Result>("GetPresouk");
        }
    
        public virtual ObjectResult<GetPretam_Result> GetPretam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretam_Result>("GetPretam");
        }
    
        public virtual ObjectResult<GetPretaref_Result> GetPretaref()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretaref_Result>("GetPretaref");
        }
    
        public virtual ObjectResult<getpretebessa_Result> getpretebessa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getpretebessa_Result>("getpretebessa");
        }
    
        public virtual ObjectResult<GetPretiaret_Result> GetPretiaret()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretiaret_Result>("GetPretiaret");
        }
    
        public virtual ObjectResult<getpretindouf_Result> getpretindouf()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getpretindouf_Result>("getpretindouf");
        }
    
        public virtual ObjectResult<GetPretipaza_Result> GetPretipaza()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretipaza_Result>("GetPretipaza");
        }
    
        public virtual ObjectResult<GetPretiss_Result> GetPretiss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretiss_Result>("GetPretiss");
        }
    
        public virtual ObjectResult<GetPretizi_Result> GetPretizi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretizi_Result>("GetPretizi");
        }
    
        public virtual ObjectResult<GetPretlemcen_Result> GetPretlemcen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPretlemcen_Result>("GetPretlemcen");
        }
    
        public virtual ObjectResult<GetTempAdrar_Result> GetTempAdrar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempAdrar_Result>("GetTempAdrar");
        }
    
        public virtual ObjectResult<GetTempaindefla_Result> GetTempaindefla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempaindefla_Result>("GetTempaindefla");
        }
    
        public virtual ObjectResult<GetTempAintemouchent_Result> GetTempAintemouchent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempAintemouchent_Result>("GetTempAintemouchent");
        }
    
        public virtual ObjectResult<GetTempAlger_Result> GetTempAlger()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempAlger_Result>("GetTempAlger");
        }
    
        public virtual ObjectResult<GetTempAnnaba_Result> GetTempAnnaba()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempAnnaba_Result>("GetTempAnnaba");
        }
    
        public virtual ObjectResult<GetTempBatna_Result> GetTempBatna()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBatna_Result>("GetTempBatna");
        }
    
        public virtual ObjectResult<GetTempBechar_Result> GetTempBechar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBechar_Result>("GetTempBechar");
        }
    
        public virtual ObjectResult<GetTempBejaia_Result> GetTempBejaia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBejaia_Result>("GetTempBejaia");
        }
    
        public virtual ObjectResult<GetTempBiskra_Result> GetTempBiskra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBiskra_Result>("GetTempBiskra");
        }
    
        public virtual ObjectResult<GetTempBlida_Result> GetTempBlida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBlida_Result>("GetTempBlida");
        }
    
        public virtual ObjectResult<GetTempBordj_Result> GetTempBordj()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBordj_Result>("GetTempBordj");
        }
    
        public virtual ObjectResult<GetTempBouira_Result> GetTempBouira()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBouira_Result>("GetTempBouira");
        }
    
        public virtual ObjectResult<GetTempBoumerdes_Result> GetTempBoumerdes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempBoumerdes_Result>("GetTempBoumerdes");
        }
    
        public virtual ObjectResult<GetTempByadh_Result> GetTempByadh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempByadh_Result>("GetTempByadh");
        }
    
        public virtual ObjectResult<GetTempChlef_Result> GetTempChlef()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempChlef_Result>("GetTempChlef");
        }
    
        public virtual ObjectResult<GetTempConsto_Result> GetTempConsto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempConsto_Result>("GetTempConsto");
        }
    
        public virtual ObjectResult<GetTempDjelfa_Result> GetTempDjelfa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempDjelfa_Result>("GetTempDjelfa");
        }
    
        public virtual ObjectResult<GetTempGhardaia_Result> GetTempGhardaia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempGhardaia_Result>("GetTempGhardaia");
        }
    
        public virtual ObjectResult<GetTempGuelma_Result> GetTempGuelma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempGuelma_Result>("GetTempGuelma");
        }
    
        public virtual ObjectResult<GetTempIllizi_Result> GetTempIllizi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempIllizi_Result>("GetTempIllizi");
        }
    
        public virtual ObjectResult<GetTempJijel_Result> GetTempJijel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempJijel_Result>("GetTempJijel");
        }
    
        public virtual ObjectResult<GetTempKhench_Result> GetTempKhench()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempKhench_Result>("GetTempKhench");
        }
    
        public virtual ObjectResult<GetTempLaghouat_Result> GetTempLaghouat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempLaghouat_Result>("GetTempLaghouat");
        }
    
        public virtual ObjectResult<GetTempMascara_Result> GetTempMascara()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempMascara_Result>("GetTempMascara");
        }
    
        public virtual ObjectResult<GetTempMedea_Result> GetTempMedea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempMedea_Result>("GetTempMedea");
        }
    
        public virtual ObjectResult<GetTempMila_Result> GetTempMila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempMila_Result>("GetTempMila");
        }
    
        public virtual ObjectResult<GetTempMosta_Result> GetTempMosta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempMosta_Result>("GetTempMosta");
        }
    
        public virtual ObjectResult<gettempmsila_Result> gettempmsila()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gettempmsila_Result>("gettempmsila");
        }
    
        public virtual ObjectResult<GetTempNaama_Result> GetTempNaama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempNaama_Result>("GetTempNaama");
        }
    
        public virtual ObjectResult<GetTempOran_Result> GetTempOran()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempOran_Result>("GetTempOran");
        }
    
        public virtual ObjectResult<GetTempOued_Result> GetTempOued()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempOued_Result>("GetTempOued");
        }
    
        public virtual ObjectResult<GetTempOuerg_Result> GetTempOuerg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempOuerg_Result>("GetTempOuerg");
        }
    
        public virtual ObjectResult<GetTempOum_Result> GetTempOum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempOum_Result>("GetTempOum");
        }
    
        public virtual ObjectResult<GetTempReliz_Result> GetTempReliz()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempReliz_Result>("GetTempReliz");
        }
    
        public virtual ObjectResult<GetTempSaida_Result> GetTempSaida()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempSaida_Result>("GetTempSaida");
        }
    
        public virtual ObjectResult<GetTempSetif_Result> GetTempSetif()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempSetif_Result>("GetTempSetif");
        }
    
        public virtual ObjectResult<GetTempSidiabbes_Result> GetTempSidiabbes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempSidiabbes_Result>("GetTempSidiabbes");
        }
    
        public virtual ObjectResult<GetTempSkikda_Result> GetTempSkikda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempSkikda_Result>("GetTempSkikda");
        }
    
        public virtual ObjectResult<GetTempSouk_Result> GetTempSouk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempSouk_Result>("GetTempSouk");
        }
    
        public virtual ObjectResult<GetTemptamen_Result> GetTemptamen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTemptamen_Result>("GetTemptamen");
        }
    
        public virtual ObjectResult<GetTempTarf_Result> GetTempTarf()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempTarf_Result>("GetTempTarf");
        }
    
        public virtual ObjectResult<gettemptebessa_Result> gettemptebessa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gettemptebessa_Result>("gettemptebessa");
        }
    
        public virtual ObjectResult<GetTempTiaret_Result> GetTempTiaret()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempTiaret_Result>("GetTempTiaret");
        }
    
        public virtual ObjectResult<gettemptindouf_Result> gettemptindouf()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gettemptindouf_Result>("gettemptindouf");
        }
    
        public virtual ObjectResult<GetTempTipaza_Result> GetTempTipaza()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempTipaza_Result>("GetTempTipaza");
        }
    
        public virtual ObjectResult<GetTempTisse_Result> GetTempTisse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempTisse_Result>("GetTempTisse");
        }
    
        public virtual ObjectResult<GetTempTizi_Result> GetTempTizi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempTizi_Result>("GetTempTizi");
        }
    
        public virtual ObjectResult<GetTempTlemcen_Result> GetTempTlemcen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempTlemcen_Result>("GetTempTlemcen");
        }
    }
}
